### ISSUE TITLE
Questions about pretraining

### ISSUE THREAD

**Issue by boqchen** [birkhoffkiki/GPFM#5]
Hi,

Thanks for the great project. I have a few questions about the pretraining.

1. Do I need to extract patches from WSI for pretraining? If so, how should the data look like, e.g., in h5 file etc.
2. How long does the training takes on your dataset?

Thanks in advance!

**Comment by birkhoffkiki** [comment]
1. If you use our released pretrained weights, then no.  If you  would like to pretrain the foundation model on your own data, it depends on the size of dataset. In our experiments, it takes about 1week for 2 H800 nodes (8 GPUs per node). In our setting, we extract 512*512 images from level 0. 
2. For downstream tasks, it is very fast. may be few ours

**Comment by boqchen** [comment]
Thanks for your prompt reply. 

How do you save these 512x512 patches? I would expect them to be 10s of millions if not hundreds. Do you just save them in one folder as png files etc. or is there a more efficient way to save them so it speeds up the training.

**Comment by birkhoffkiki** [comment]
The file structure is similar to following lines:
├── ACROBAT2023 (dataset name)
│   ├── images
│   │   ├── 100_ER (slide name)
│   │   │        ├── x_y_size_size.jpg (pathc name)

Then we built an index for all files, and saved them into a json file:
{"slide_name": [path1, path2, ....],
xxxx
}
to read data, read the json first, and then iterate all paths

**Comment by JAAY-AI** [comment]
@birkhoffkiki 非常棒的工作，我最近也在学习病理大模型，想学习一下模型的预训练细节，请问你们在准备数据集的时直接存储所有WSI中切的40X倍率下512px大小的patch，准备了多大的硬盘存储空间呀（存这么多patch感觉要消耗很多碎片空间）

**Comment by birkhoffkiki** [comment]
@LiuJin629 16TB的SSD应该够了。避免碎片空间，你也可以用h5或者numpy之类的方式保存数据。

**Comment by JAAY-AI** [comment]
好的，感谢

---- Replied Message ----
| From | Jiabo ***@***.***> |
| Date | 04/14/2025 12:01 |
| To | birkhoffkiki/GPFM ***@***.***> |
| Cc | LiuJin ***@***.***>,
Mention ***@***.***> |
| Subject | Re: [birkhoffkiki/GPFM] Questions about pretraining (Issue #5) |

@LiuJin629 16TB的SSD应该够了。避免碎片空间，你也可以用h5或者numpy之类的方式保存数据。

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***>

birkhoffkiki left a comment (birkhoffkiki/GPFM#5)

@LiuJin629 16TB的SSD应该够了。避免碎片空间，你也可以用h5或者numpy之类的方式保存数据。
